SET LINESIZE 1000

COLUMN SCHEDULE_NAME FORMAT A30
COLUMN PROGRAM_NAME FORMAT A30
COLUMN SCHEDULE_OWNER FORMAT A30
COLUMN PROGRAM_OWNER FORMAT A30
COLUMN COMMENTS FORMAT A50

SELECT J.OWNER,
       J.JOB_NAME,
       J.ENABLED,
       J.STATE,
       J.PROGRAM_OWNER,
       J.PROGRAM_NAME,
       J.SCHEDULE_OWNER,
       J.SCHEDULE_NAME,
       J.RUN_COUNT,
       J.LAST_START_DATE,
       J.LAST_RUN_DURATION,
       J.NEXT_RUN_DATE,
       J.COMMENTS
  FROM sys.DBA_SCHEDULER_JOBS J
 WHERE OWNER = 'SYSTEM' AND JOB_NAME = 'DB_BCK';

prompt exec SYS.DBMS_SCHEDULER.ENABLE (name  => 'SYSTEM.DB_BCK');;
prompt exec SYS.DBMS_SCHEDULER.DISABLE(name  => 'SYSTEM.DB_BCK' ,force => TRUE);;
