CREATE USER RO_CC
  IDENTIFIED BY "H0tsummerd2y**"
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP;

  GRANT CONNECT TO RO_CC;
  GRANT OEM_MONITOR TO RO_CC;

  ALTER USER RO_CC DEFAULT ROLE ALL;
  GRANT SELECT ANY DICTIONARY TO RO_CC;
  GRANT UNLIMITED TABLESPACE TO RO_CC;
