CREATE PROFILE APPUSER LIMIT
  SESSIONS_PER_USER UNLIMITED
  CPU_PER_SESSION UNLIMITED
  CPU_PER_CALL UNLIMITED
  CONNECT_TIME UNLIMITED
  IDLE_TIME UNLIMITED
  LOGICAL_READS_PER_SESSION UNLIMITED
  LOGICAL_READS_PER_CALL UNLIMITED
  COMPOSITE_LIMIT UNLIMITED
  PRIVATE_SGA UNLIMITED
  FAILED_LOGIN_ATTEMPTS 10
  PASSWORD_LIFE_TIME UNLIMITED
  PASSWORD_REUSE_TIME 1800
  PASSWORD_REUSE_MAX 10
  PASSWORD_LOCK_TIME 0.0006
  PASSWORD_GRACE_TIME 7
  PASSWORD_VERIFY_FUNCTION VERIFY_PASSWORD;
