ALTER USER EMPI GRANT CONNECT THROUGH &username;
ALTER USER EMPIRO GRANT CONNECT THROUGH &username;
ALTER USER EMPIRPT GRANT CONNECT THROUGH &username;
ALTER USER PROVIDERRO GRANT CONNECT THROUGH &username;
