BREAK ON DEPARTMENT_ID ON JOB_ID DUPLICATES
COMPUTE SUM OF SALARY ON DEPARTMENT_ID
COMPUTE AVG OF SALARY ON JOB_ID

SELECT DEPARTMENT_ID,
         JOB_ID,
         LAST_NAME,
         SALARY
    FROM hr.EMP_DETAILS_VIEW
   WHERE JOB_ID IN ('SH_CLERK', 'SA_MAN') AND DEPARTMENT_ID IN (50, 80)
  ORDER BY DEPARTMENT_ID, JOB_ID;
