column R_HOSTNAME NEW_VALUE R_HOSTNAME
column R_SERVICE_NAME NEW_VALUE R_SERVICE_NAME
column R_DBSNMP NEW_VALUE R_DBSNMP
column R_SYSCC NEW_VALUE R_SYSCC
column R_ROCC NEW_VALUE R_ROCC
column R_SYSDBA NEW_VALUE R_SYSDBA
column R_SYSTEM NEW_VALUE R_SYSTEM

column R_SYSTEM_USERNAME NEW_VALUE R_SYSTEM_USERNAME
column R_SYSTEM_PASSWORD NEW_VALUE R_SYSTEM_PASSWORD
column R_CONNECT_STRING NEW_VALUE R_CONNECT_STRING

SELECT '&SYSTEM' R_SYSTEM FROM DUAL;
SELECT '&SYSDBA' R_SYSDBA FROM DUAL;
SELECT '&ROCC' R_ROCC FROM DUAL;
SELECT '&SYSCC' R_SYSCC FROM DUAL;
SELECT '&DBSNMP' R_DBSNMP FROM DUAL;
SELECT '&SERVICE_NAME' R_SERVICE_NAME FROM DUAL;
SELECT '&HOSTNAME' R_HOSTNAME FROM DUAL;

SELECT '&SYSTEM_USERNAME' R_SYSTEM_USERNAME FROM DUAL;
SELECT '&SYSTEM_PASSWORD' R_SYSTEM_PASSWORD FROM DUAL;
SELECT '&CONNECT_STRING' R_CONNECT_STRING FROM DUAL;


define R_HOSTNAME
define R_SERVICE_NAME
define R_DBSNMP
define R_SYSCC
define R_ROCC
define R_SYSDBA
define R_SYSTEM

define R_SYSTEM_USERNAME
define R_SYSTEM_PASSWORD
define R_CONNECT_STRING
